---
- hosts: 127.0.0.1
  sudo: yes
  remote_user: runuser
  tasks:

    - name: Install apt-package dependencies
      apt: >
        name="{{ item }}"
        state="present"
        force=yes
      with_items:
        - python-pip
        - supervisor
        - gunicorn
        - nginx 

    - name: Copy the requirements.txt file to tmp directory
      copy: src="requirements.txt" dest="/tmp"

    - name: Create belong log directory
      file: >
      path="//var/log/belong/"
      state="directory"
      owner=runuser
      group=runuser
      mode=0755

    - name: Installing pip requirements.
      pip: requirements="/tmp/requirements.txt"  

    - name: Copy the supervisor configuration file for gunicorn
      copy: >
        src=gunicorn_process.conf
        dest=/etc/supervisor/conf.d/gunicorn_process.conf

    - name: Copy the nginx configuration
      copy: >
        src=web_app_nginx_conf
        dest=/etc/nginx/sites-available/web_app

    - name: Create softlink for sites-enabled
      file: >
        src=/etc/nginx/sites-available/web_app
        dest=/etc/nginx/sites-enabled/web_app
        state=link
        owner=runuser
        group=runuser

    - name: Restart nginx
      service: name=nginx state=restarted

