---
- hosts: 127.0.0.1
  sudo: yes
  remote_user: runuser
  tasks:

    # Example that prints the loopback address and gateway for each host
    - debug: msg="System"

    - debug: msg="System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: "ansible_default_ipv4.gateway is defined"
    
    - shell: /usr/bin/uptime
      register: result
    
    - debug: var=result verbosity=2
    
    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname] verbosity=4