---
- hosts: 127.0.0.1
  become: yes
  remote_user: centos
  tasks:

    - name: "Create admin group"
      group:
        name: "admin"
        state: "present"

    - name: "Create admin user - 'admin_user'"
      user:
        name: "admin"
        group: "admin"
        home: "/home/admin"
        comment: "admin user"
        shell: "/bin/bash"
        state: "present"  

    - name: "Create directory /etc/sudoers.d"
      file:
        path: "/etc/sudoers.d"
        state: "directory"
        owner: "root"
        group: "root"
        mode: 0755  

    - name: "Include hello world in your file"
      lineinfile:
        dest: "/tmp/hello"
        line: "Hello World"
        state: "present"

    - name: Create Symlink
      file:
        src: /tmp/hello
        dest: /tmp/hellosym
        state: link

    # Example that prints the loopback address and gateway for each host
    - debug: msg: "System"

    - debug: msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: "ansible_default_ipv4.gateway is defined"
    
    - shell: /usr/bin/uptime
      register: result
    
    - debug: var=result verbosity=2
    
    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname] verbosity=4

    - name: Copy the public keys to all machines
      debug: var=hostvars[inventory_hostname] verbosity=4