---
- hosts: 192.168.122.1

  sudo: yes
  remote_user: hellodk
  tasks:
    - name: Updates apt cache
      action: apt update_cache=true

    - name: install libtool
      apt:
        name: {{ item }}
        state: present
      with_items:
        - autoconf
        - autoconf
        - zlib1g  
        - zlib1g-dev
        - libjpeg8-dev
        - checkinstall
        - sqlite3  
        - libsqlite3-dev
        - libcurl3
        - libcurl4-gnutls-dev
        - libpcre3-dev
        - speex
        - libspeex-dev
        - libspeexdsp-dev
        - libldns-dev
        - libedit-dev
