# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "mwrock/Windows2012R2"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 300
  config.vm.synced_folder "./", "/home/vagrant/synced_folder", :mount_options => ["dmode=777", "fmode=666"]
  config.vm.network :private_network, guest: 3389, host: 3389, id: 'rdp', auto_correct: true, ip: "192.168.10.35"
#  ansiblem.vm.network :forwarded_port, 

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 2048
  end
end
