---
- hosts: all
  become: yes
  remote_user: centos
  # gather_facts: no
  tasks:

    - name: Create demo log directory
      file:
        path: "/var/log/demo/"
        state: "directory"
        owner: "admin"
        group: "admin"
        mode: 0755

    - name: Execute a shell command
      shell:
        cmd: 'ls -ltr'