---
- hosts: all
  become: yes
  remote_user: vagrant
  # gather_facts: yes
  tasks:

    - name: "Create Bhardwaj user"
    # - name: "Create admin '{{ user }}' "
      user: 
        name: "Bhardwaj"
        # name: '{{ user }}'
        state: "present"
