---
- hosts: 127.0.0.1
  become: yes
  # become_user: vagrant
  tasks:

    # - name: os update
    #   apt:
    #     update_cache: yes

    - name: install pre softwares
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common