---
- hosts: all
  become: true
  serial: 2

  vars:
    ansible_become_pass: vagrant

  tasks:

    - name: install ntp
      apt:
        pkg: ntp
        state: present
      tags:
        - abc
      notify:
        - run update


    - name: install vim
      apt:
        pkg: vim
        state: present
      tags:
        - abc
        - ijk

    - name: start ntp service
      service:
        name: ntp
        state: started
        enabled: true
      tags:
        - xyz

  handlers:

    - name: run update
      apt:
        update_cache: "yes"


    - name: run update 2
      apt:
        update_cache: "yes"

    # - name: restart apache
    #   service:
    #     name: "apache2/httpd"
